const photoSlides = [
  // "https://www.boucheriebocquet.fr/wp-content/uploads/2024/09/Wellington-de-Chasse.jpg",
  // "https://www.boucheriebocquet.fr/wp-content/uploads/2024/02/AFFICHE-BOUCHERIES-FINAL-Publication-Instagram-1.jpg",
  // "https://www.boucheriebocquet.fr/wp-content/uploads/2021/02/IMG_7968-2-edited-scaled.jpg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2020/03/IMG_5239.png",
  // "https://www.boucheriebocquet.fr/wp-content/uploads/2019/03/100_0055_ws1036603047.jpg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2018/09/race-reconnue-zoom.jpg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2017/03/Little-marcel-2.jpg",
  // "https://www.boucheriebocquet.fr/wp-content/uploads/2017/03/droppedImage.jpg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-1.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-2.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-3.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-4.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-5.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-6.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-7.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-8.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-9.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-10.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-11.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-12.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-13.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-14.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-15.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-16.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-17.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-18.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-19.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-20.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-21.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-22.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-23.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-24.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-25.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-26.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-28.jpeg",
  "https://www.boucheriebocquet.fr/wp-content/uploads/2025/03/meatTop-29.jpeg",
];
